### PR TITLE
Modified Widthwatcher for stability at low health

### PR DESCRIPTION
**Pull request by ebshimizu**
Since the numbers break up the bar (at least for hots) at low health, the detected health bar is sometimes broken up into parts. The algorithm has been adjusted to track the rightmost "fragment" within the largest observed health bar so far and calculates fill based off of that. For left/top/right filling bars, the change should be fairly simple but has not been implemented yet.

Definitely check this one before merging to see it it works, I may have accidentally left some references to my keyboard wrapper.

### CODE REVIEW

**Comment by jjensn** [comment]
I'm going to copy it into my local repo and give it a shot before merging.

I've also been considering another strategy -- one that would work for Overwatch as well. I may end up merging this and then working through another method. Will keep you posted

**Comment by ebshimizu** [comment]
I added OSC output as an endpoint (versus REST) but did it in a way that kinda screwed up my repo's history. If you would like these changes in separate requests I can take a bit of time tomorrow to separate it.

**Comment by jjensn** [comment]
The OSC stuff looks good; I'm still on the fence on the new rectangle detection method. In my tests, I didn't have as much luck with it finding the proper rectangle. For me, the detection on the green health bar has worked the best.

Can you split the OSC stuff out and submit a new PR?

**Comment by ebshimizu** [comment]
Yup I'll do that this week. Will close this PR and add the OSC one when complete.

The rectangle detection should still be the same, the adjustment is to how the "fullness" of the rectangle is computed. Will keep the change around in a branch in my fork for reference after separation.

**Comment by jjensn** [comment]
Do you have a picture laying around somewhere with the rectangle drawn? Maybe it would be easier for me to understand if I saw it.

I have my lights fade to 0 when I die (based on the respawn bar timer), and that bar collapses to the center -- I know you had said it would be trivial to add support for that, but I still am a little unclear on the new method.

**Comment by ebshimizu** [comment]
hm, not lying around but given a little time I could go make a figure demonstrating it. And i forgot about the respawn timer and haven't tested this with that.

**Comment by ebshimizu** [comment]
OSC request in #3

**Pull request closed without merging**
